default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: misrsmok_sUser
  password: milktoast!
  host: localhost

development:
  <<: *default
  database: misrsmok_testapp1_development